name: Twitter Bot Check

on:
  schedule:
    - cron: '0 10 * * *' # UTC
  workflow_dispatch:

jobs:
  check-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Python 3
      run: |
        sudo apt-get update
        sudo apt-get install python3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run script
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python bot_check.py